### ISSUE TITLE
Correlation analysis only among a select amount of expression stages

### ISSUE THREAD

**Issue by CodingBash** [CodingBash/FlyCAGE#43]
Will only do correlation analysis among a select amount of expression stages (instead of all available correlation stages). Thus, the user can determine what other genes are correlated based on a subset of stages.

This story also includes support of default expression stage groups.

TASKS:

- [x] Determine expression stage groups

- [x] Front-end UI updates to allow selection of multiple expression stage groups

- [x] Front-end UI Input Form

- [ ] Front-end UI Result Display

- [ ] Back-end Java logic to facilitate expression stage input

- [ ] Back-end Java logic to conduct correlation analysis only among the expression stage result

- [ ] Any other changes to help documents, plot dynamic changes, etc. to account for different expression stage set

**Comment by MortimerLab** [comment]
Expression Stage Groups are in attached file (each group is a separate sheet). There are 5 groups (embryogenesis, development, tissue, treatment, cell line) - the only overlap is between embryogenesis and development.
[FlyCorr_ExprStages.xlsx](https://github.com/CodingBash/fly-correlation-webapp/files/1031903/FlyCorr_ExprStages.xlsx)
